id: P006697
initial_creation_type: ocr
source_metadata:
  id: bdr:W25090
  title: མཚོ་ཆེན་ཁྲི་གཤོག་རྒྱལ་མོའི་མཚོ་བསང་དང་གནས་ཡིག་གནས་བསྟོད་སྣ་ཚོགས
  author: ''
  volumes:
    46c18b04ad45469f8e4eb4e94ab2194c:
      image_group_id: I1PD356
      title: ''
      volume_number: 1
      total_pages: 102
      base_file: v001.txt
