id: I950BCE4B
legacy_id: P006697
ocr_import_info:
  bdrc_scan_id: W25090
  source: bdrc
  ocr_info:
    timestamp: '2020-03-23T12:49:07'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T05:56:37.668451+00:00'
last_modified: 2022-09-02 13:56:49.865023
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W25090
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW25090
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: མཚོ་ཆེན་ཁྲི་གཤོག་རྒྱལ་མོའི་མཚོ་བསང་དང་གནས་ཡིག་གནས་བསྟོད་སྣ་ཚོགས།
statistics:
  ocr_word_mean_confidence_index: 0.9160095521278964
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I1PD356:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD356
      total_pages: 102
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1PD356.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9160095521278964
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
